### ISSUE TITLE
Preciser le mail de contact dans les offres

### ISSUE THREAD

**Issue by allan-simon** [jlondiche/job-board-php#5]
Si je link une des offres a un potentiel candidat et qu'il ne connait pas specialement tes methodes de recrutements, il peut finir de l'offre en se demandant "ok what's next?" , et du coup rajouter a la fin de chaque .md d'offre ton contact et l'objet de l'email pourrait faciliter cela ? 

my 2 cents

**Comment by jlondiche** [comment]
bonne idée, je modifie ! Merci Allan
